# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
      - master
  paths:
    exclude:
      - LICENSE
      - README.md

jobs:
- job: Package
  strategy:
    matrix:
      MINGW32:
        target: 'i686'
        prefix: 'mingw32'
        MSYSTEM: 'MINGW32'
      MINGW64:
        target: 'x86_64'
        prefix: 'mingw64'
        MSYSTEM: 'MINGW64'
      UCRT64:
        target: 'ucrt-x86_64'
        prefix: 'ucrt64'
        MSYSTEM: 'UCRT64'
      CLANG32:
        target: 'clang-i686'
        prefix: 'clang32'
        MSYSTEM: 'CLANG32'
      CLANG64:
        target: 'clang-x86_64'
        prefix: 'clang64'
        MSYSTEM: 'CLANG64'
  pool:
    vmImage: 'windows-latest'
  
  steps:
  - pwsh: |
      git config core.autocrlf false
      rm .git/index
      git reset --hard
    displayName: "Fix CRLF"

  - pwsh: |
      $env:PATH="$PATH;C:\msys64\$(prefix)\bin;C:\msys64\usr\bin;"
      C:\msys64\usr\bin\pacman.exe -Syu --noconfirm
      C:\msys64\usr\bin\pacman.exe -S --noconfirm mingw-w64-$(target)-binutils
      cd mingw-w64-git
      C:\msys64\usr\bin\bash.exe C:\msys64\usr\bin\makepkg-mingw -s --noconfirm
    displayName: "Package git"
    env:
      MSYSTEM: $(MSYSTEM)

  - pwsh: |
      $env:PATH="$PATH;C:\msys64\$(prefix)\bin;C:\msys64\usr\bin;"
      cd mingw-w64-git-lfs
      C:\msys64\usr\bin\bash.exe C:\msys64\usr\bin\makepkg-mingw -s --noconfirm
    displayName: "Package git-lfs"
    env:
      MSYSTEM: $(MSYSTEM)

  - pwsh: |
      git clone https://github.com/git-for-windows/build-extra.git
    displayName: "Clone build-extra from official repo"

  - pwsh: |
      $env:PATH="$PATH;C:\msys64\$(prefix)\bin;C:\msys64\usr\bin;"
      cd build-extra/mingw-w64-git-credential-manager
      C:\msys64\usr\bin\bash.exe -c "makepkg-mingw -s --noconfirm"
    displayName: "Package gcm"
    env:
      MSYSTEM: $(MSYSTEM)

  - task: CopyFiles@2
    inputs:
      contents: '**/*.pkg.tar.*' 
      targetFolder: $(build.artifactstagingdirectory)
      flattenFolders: true
      preserveTimestamp: true
    displayName: "Copy git packages"

  - task: PublishBuildArtifacts@1
    inputs:
      ArtifactName: 'publish'

- job: RepoAdd
  dependsOn: Package
  pool:
    vmImage: 'windows-latest'

  steps:
  - task: DownloadPipelineArtifact@2
    inputs:
      artifact: 'publish'
      path: $(Build.SourcesDirectory)/repo
    displayName: "Download packages"

  - pwsh: |
      $env:PATH="$PATH;C:\msys64\usr\bin;"
      cd repo
      C:\msys64\usr\bin\bash.exe -c "repo-add git-for-windows.db.tar.gz *"
    displayName: "Run repo-add"

  - task: CopyFiles@2
    inputs:
      contents: 'repo/*' 
      targetFolder: $(build.artifactstagingdirectory)
      flattenFolders: true
      preserveTimestamp: true
    displayName: "Copy repo"
